version: "3.5"

services:
  web:
    image: webdevops/php-nginx:7.3
    working_dir: /app
    ports:
      - 8080:80
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

